export default {
  GAME_OF_MADNESS_SET_CONTRACT_INSTANCE: 'GAME_OF_MADNESS_SET_CONTRACT_INSTANCE',

  GAME_OF_MADNESS_HANDLE_ACTIVE_TAB_CHANGE: 'GAME_OF_MADNESS_HANDLE_ACTIVE_TAB_CHANGE',
  GAME_OF_MADNESS_HANDLE_CURRENT_GAME_CHANGE: 'GAME_OF_MADNESS_HANDLE_CURRENT_GAME_CHANGE',

  GAME_OF_MADNESS_GET_HOSTED_GAMES: 'GAME_OF_MADNESS_GET_HOSTED_GAMES',
  GAME_OF_MADNESS_GET_USER_GAMES: 'GAME_OF_MADNESS_GET_USER_GAMES',
  GAME_OF_MADNESS_HANDLE_ADD_TO_USER_GAMES: 'GAME_OF_MADNESS_HANDLE_ADD_TO_USER_GAMES',
  GAME_OF_MADNESS_HANDLE_CHANGE_USER_GAME_STATUS: 'GAME_OF_MADNESS_HANDLE_CHANGE_USER_GAME_STATUS',

  GAME_OF_MADNESS_HANDLE_GAME_HOSTED_EVENT: 'GAME_OF_MADNESS_HANDLE_GAME_HOSTED_EVENT',
  GAME_OF_MADNESS_HANDLE_GAME_JOINED_EVENT: 'GAME_OF_MADNESS_HANDLE_GAME_JOINED_EVENT',
  GAME_OF_MADNESS_HANDLE_BET_RAISED_EVENT: 'GAME_OF_MADNESS_HANDLE_BET_RAISED_EVENT',
  GAME_OF_MADNESS_HANDLE_GAME_ENDED_EVENT: 'GAME_OF_MADNESS_HANDLE_GAME_ENDED_EVENT',
};