export default {
  GAME_OF_MADNESS_SET_CONTRACT_INSTANCE: 'GAME_OF_MADNESS_SET_CONTRACT_INSTANCE',

  GAME_OF_MADNESS_HANDLE_ACTIVE_TAB_CHANGE: 'GAME_OF_MADNESS_HANDLE_ACTIVE_TAB_CHANGE',
  GAME_OF_MADNESS_HANDLE_CURRENT_GAME_CHANGE: 'GAME_OF_MADNESS_HANDLE_CURRENT_GAME_CHANGE',

  GAME_OF_MADNESS_GET_HOSTED_GAMES: 'GAME_OF_MADNESS_GET_HOSTED_GAMES',
  GAME_OF_MADNESS_GET_USER_GAMES: 'GAME_OF_MADNESS_GET_USER_GAMES',
};