export default {
  SET_CURRENT_METAMASK_ACCOUNT: 'SET_CURRENT_METAMASK_ACCOUNT',
  SET_ETH_PRICE: 'SET_ETH_PRICE',

  GUESS_NUMBER_GAME_SET_CONTRACT_INSTANCE: 'GUESS_NUMBER_GAME_SET_CONTRACT_INSTANCE',

  GUESS_NUMBER_GAME_HANDLE_CURRENT_GAME_CHANGE: 'GUESS_NUMBER_GAME_HANDLE_CURRENT_GAME_CHANGE',
  GUESS_NUMBER_GAME_HANDLE_ACTIVE_TAB_CHANGE: 'GUESS_NUMBER_GAME_HANDLE_ACTIVE_TAB_CHANGE',

  GUESS_NUMBER_GAME_GET_CURRENT_GAME_FIELDS: 'GUESS_NUMBER_GAME_GET_CURRENT_GAME_FIELDS',

  GUESS_NUMBER_GAME_GET_HOSTED_GAMES: 'GUESS_NUMBER_GAME_GET_HOSTED_GAMES',
  GUESS_NUMBER_GAME_GET_USER_GAMES: 'GUESS_NUMBER_GAME_GET_USER_GAMES',
  GUESS_NUMBER_GAME_HANDLE_GAME_HOSTED_EVENT: 'GUESS_NUMBER_GAME_HANDLE_GAME_HOSTED_EVENT',
  GUESS_NUMBER_GAME_HANDLE_GAME_JOINED_EVENT: 'GUESS_NUMBER_GAME_HANDLE_GAME_JOINED_EVENT',
  GUESS_NUMBER_GAME_HANDLE_GAME_ENDED_EVENT: 'GUESS_NUMBER_GAME_HANDLE_GAME_ENDED_EVENT',

  GUESS_NUMBER_GAME_HANDLE_ADD_TO_USER_GAMES: 'GUESS_NUMBER_GAME_HANDLE_ADD_TO_USER_GAMES',
  GUESS_NUMBER_GAME_HANDLE_CHANGE_USER_GAME_STATUS: 'GUESS_NUMBER_GAME_HANDLE_CHANGE_USER_GAME_STATUS',

  GUESS_NUMBER_GAME_TRIGGER_CURRENT_GAME_TAB_SPINNER: 'GUESS_NUMBER_GAME_TRIGGER_CURRENT_GAME_TAB_SPINNER',
};