export default {
  SET_CONTRACT_INSTANCE: 'SET_CONTRACT_INSTANCE',

  HANDLE_CURRENT_GAME_ID_CHANGE: 'HANDLE_CURRENT_GAME_ID_CHANGE',
  HANDLE_ACTIVE_TAB_CHANGE: 'HANDLE_ACTIVE_TAB_CHANGE',

  GET_CURRENT_GAME_FIELDS: 'GET_CURRENT_GAME_FIELDS',
};